### ISSUE TITLE
安装完成后运行失败

### ISSUE THREAD

**Issue by gdsdfn75** [zhengchen1999/RGT#14]
您好，这是一个非常棒的工作。但我按照requirements.txt在python=3.8的环境中安装并执行训练后，出现以下错误：
Traceback (most recent call last):
  File "basicsr/train.py", line 215, in <module>
    train_pipeline(root_path)
  File "basicsr/train.py", line 117, in train_pipeline
    tb_logger = init_tb_loggers(opt)
  File "basicsr/train.py", line 25, in init_tb_loggers
    tb_logger = init_tb_logger(log_dir=osp.join(opt['root_path'], 'tb_logger', opt['name']))
  File "/home/student01/RGT-main/basicsr/utils/dist_util.py", line 80, in wrapper
    return func(*args, **kwargs)
  File "/home/student01/RGT-main/basicsr/utils/logger.py", line 120, in init_tb_logger
    from torch.utils.tensorboard import SummaryWriter
  File "/home/student01/anaconda3/envs/RGT/lib/python3.8/site-packages/torch/utils/tensorboard/__init__.py", line 4, in <module>
    LooseVersion = distutils.version.LooseVersion
AttributeError: module 'distutils' has no attribute 'version'
您能帮看一下是哪里的问题吗？非常感谢！

**Comment by zhengchen1999** [comment]
请问是新建的conda环境吗？如果是在已有环境中安装，可能会有库的版本不适配，导致问题。
可以尝试按照[Dependencies](https://github.com/zhengchen1999/RGT?tab=readme-ov-file#%EF%B8%8F-dependencies)，重新安装一个新的环境。

**Comment by gdsdfn75** [comment]
> 请问是新建的conda环境吗？如果是在现有环境中安装，可能会有库的版本不改装，导致问题。 可以尝试按照[依赖关系](https://github.com/zhengchen1999/RGT?tab=readme-ov-file#%EF%B8%8F-dependencies)，重新安装一个新的环境。

感谢您的回复，我再重新安装一下。

**Comment by strongweight** [comment]
在这个github中的这个解决方法可以解决我的问题
https://github.com/pytorch/pytorch/issues/69894
pip install setuptools==59.5.0
