### ISSUE TITLE
about test

### ISSUE THREAD

**Issue by CarrieWang0319** [zhengchen1999/RGT#7]
There is no problem when running the test on Windows, but the following error occurs when running on the cloud. Is there any solution? Or can you provide me with a solution? Thank you very much。

Name RGTModel is not found, use name: RGTModel_basicsr!
Traceback (most recent call last):
  File "basicsr/test.py", line 44, in <module>
    test_pipeline(root_path)
  File "basicsr/test.py", line 34, in test_pipeline
    model = build_model(opt)
  File "/usr/local/lib/python3.8/dist-packages/basicsr/models/__init__.py", line 26, in build_model
    model = MODEL_REGISTRY.get(opt['model_type'])(opt)
  File "/usr/local/lib/python3.8/dist-packages/basicsr/utils/registry.py", line 71, in get
    raise KeyError(f"No object named '{name}' found in '{self._name}' registry!")
KeyError: "No object named 'RGTModel' found in 'model' registry!"

**Comment by zhengchen1999** [comment]
There is a problem with your Python environment, you can follow the instructions [here](https://github.com/zhengchen1999/RGT?tab=readme-ov-file#%EF%B8%8F-dependencies) to install a new environment.

**Comment by CarrieWang0319** [comment]
Well, I have considered this problem, so I manually changed the cloud environment to be the same as on Windows, but this error still occurs. Is there any other solution?

**Comment by zhengchen1999** [comment]
From your error message, it looks like your basicsr path is: /usr/local/lib/python3.8/dist-packages/basicsr. However, if the installation was successful, then the basicsr path should be within the RGT directory. This issue might have occurred because you had previously installed BasicSR in your current environment, or the **python setup.py develop** command did not execute successfully. 
Note, if you installed basicsr via **pip install basicsr** before, then this environment can't be used to configure RGT. You must create a new environment without basicsr using **conda create**.

**Comment by CarrieWang0319** [comment]
Thank you for your reminder! Suddenly enlightened!
